// ─── THE DECKS ────────────────────────────────────────────────────────────
//
// Four kinds of round:
//
//   pick    — everyone taps a name. Most-picked drinks. Fast and personal.
//   text    — everyone types freely, then votes. Most votes drinks.
//   hand    — a prompt with blanks. Dealt seven cards, play one (or two).
//   person  — a hand round where the prompt names somebody in the room.
//             Marked by a {player} token, filled with a real player's name.
//
// All original writing. Nothing here is lifted from any published deck.
// Add your own — it's just strings.

// ─── pick a person ────────────────────────────────────────────────────────

const PICK = [
  "Who here would you want to be a forever conjoined twin to? No separation, ever.",
  "Plane goes down in the Andes. Rations run out. Who do we eat first?",
  "One of us is going in the volcano to save the rest. Nominate.",
  "Whose search history would end this friendship group tonight?",
  "Who is the worst person here and we all quietly know it?",
  "Who breaks first under interrogation? Not even torture. Just a stern voice.",
  "Who is most likely to join a cult? Joining, not leading.",
  "Who is most likely to lead the cult?",
  "You get one phone call from jail. Who do you absolutely not call?",
  "Who dies first in the horror film?",
  "Who survives the horror film purely by being too annoying to kill?",
  "Who would sell this entire group to the government for a moderate sum?",
  "Who is going to jail first, and for exactly what we all expect?",
  "Who would sell a kidney to buy a jet ski?",
  "Whose nudes are already on a server somewhere?",
  "Who would you least want performing emergency surgery on you?",
  "Who is secretly the villain of this story?",
  "Six hours stuck in a broken lift. Who is the worst possible companion?",
  "Whose funeral would have the lowest turnout?",
  "Whose eulogy would accidentally be the funniest thing ever written?",
  "Who has definitely been walked in on and never spoken of it?",
  "Who would you trust least to hold your passport for ten minutes?",
  "Who becomes a motivational speaker with zero relevant qualifications?",
  "Who would be replaced by a chatbot and nobody would notice for a month?",
  "Zombies. We can only carry one person. Who gets left on the roof?",
  "Who would make the most insufferable ghost?",
  "Who starts the fistfight? Separate question: who wins it?",
  "Who would you let name your firstborn child, legally, no take-backs?",
  "Who is most likely to have a second phone, and for the obvious reason?",
  "Who eats the unlabelled tin from the back of the cupboard on a dare?",
  "Whose parents secretly prefer the rest of us?",
  "Who would fake their own death and then post about it from the funeral?",
  "Who is most likely to be detained at an airport over a misunderstanding?",
  "You need an alibi for something serious. Who do you trust to lie for you?",
  "Who would last longest on a deserted island? Who is eaten on day two?",
  "Who would rat the rest of us out first, and for the smallest reward?",
  "Who would you not trust alone in your house for ten minutes?",
  "Whose phone, unlocked and read aloud, would ruin the most lives?",
  "Who would be the worst parent, and be completely unaware of it?",
  "Who peaked earliest and hardest?",
  "Who is going to be a nudist by sixty?",
  "Who would you be least surprised to see on the news?",
  "Who would you want beside you in a brawl? Who is already in the car?",
  "Whose family is the most unhinged?",
  "Who has the worst secret in this room right now?",
  "Who would have an affair and be caught within a week?",
  "Who would you trust to clear your browser history when you die?",
  "Who is going to die doing something entirely preventable?",
  "One of us goes under the bus to save the rest. Push.",
  "Who would survive a week inside? Who would enjoy it?",
  "Who has the worst taste in partners, historically and consistently?",
  "Who would you leave holding the baby, literally?",
  "Who has cried during sex and told nobody?",
  "Who is the most likely to end up on a register of some kind?",
  "Who would take the longest to be reported missing?",
];

// ─── type your own ────────────────────────────────────────────────────────

const TEXT = [
  "The group chat leaks tomorrow. Which message ends a career?",
  "Invent a law that would immediately ruin exactly one person in this room.",
  "Your tombstone, after an extremely stupid death. What does it say?",
  "Title of your autobiography.",
  "The worst possible sentence to hear from your surgeon, mid-operation.",
  "You are a cult leader. State your one non-negotiable rule.",
  "The reason you have been permanently banned from a country.",
  "First line of the new national anthem.",
  "The worst superpower that technically still counts as a superpower.",
  "Pitch your reality TV show in one sentence.",
  "The worst thing to say at a funeral. Bonus points if it is true.",
  "The unhinged message you send at 3am and regret at 9am.",
  "Finish the ad: wanted, one flatmate, must be willing to ___",
  "Your final meal on death row. Be unnecessarily specific.",
  "What is that smell?",
  "The tattoo that would quietly ruin the rest of your life.",
  "Explain your criminal record in exactly five words.",
  "You are being deported. State the official reason.",
  "The worst possible thing to find in a hotel room.",
  "A new Olympic sport that would produce genuinely upsetting footage.",
  "What did you do that got the group banned from the venue?",
  "The single worst piece of advice you could give a child.",
  "Your dating profile bio, written honestly.",
  "What is written in your hospital file, in the doctor's handwriting?",
  "The reason the police were called last night.",
  "What is the worst thing you have ever been forgiven for?",
  "Describe your worst physical feature as an estate agent would.",
  "The last thing you want to hear from a tattooist.",
  "What is in the bag?",
  "Your safe word, and the story behind it.",
  "What woke the entire street at four in the morning?",
  "The reason you are no longer allowed at that particular Bunnings.",
];

// ─── prompts with blanks ──────────────────────────────────────────────────
// Use ___ for each blank. Two blanks means everyone plays two cards.

const BLACK = [
  "Come for the beaches, stay for ___.",
  "I got the job. Turns out they were mainly after ___.",
  "My therapist has started taking notes about ___.",
  "The reason the party ended: ___.",
  "Nobody warned me that marriage is ninety percent ___.",
  "The council has voted unanimously to ban ___.",
  "In my defence, the invitation said nothing about ___.",
  "Australia's next great export: ___.",
  "What is currently ruining my life? ___.",
  "The results came back. It is ___.",
  "I am not saying it was ___, but it was absolutely ___.",
  "The new safety induction opens with ___ and closes with ___.",
  "What did I bring to the potluck? ___.",
  "The last thing you want to hear on a first date: ___.",
  "I have decided to sell everything and dedicate my life to ___.",
  "What is under the tarp? ___.",
  "The court found me guilty of ___ but sentenced me for ___.",
  "Every family has one. Ours has ___.",
  "The retirement gift nobody asked for: ___.",
  "Why am I on a watchlist? ___.",
  "My legacy will be ___.",
  "The single greatest threat to this friendship group is ___.",
  "What ruined the honeymoon? ___.",
  "The new office policy exists entirely because of ___.",
  "I do not drink anymore. Not since ___.",
  "One thing to rescue from a house fire: ___.",
  "The school reunion was ruined by ___.",
  "How did I lose the deposit? ___, followed immediately by ___.",
  "The plumber has never seen anything like ___.",
  "Tonight on the news: local man arrested with ___.",
  "The group chat has renamed itself ___.",
  "What am I bringing to the apocalypse? ___.",
  "The cruise brochure failed to mention ___.",
  "My personal brand is ___.",
  "Do not, under any circumstances, search for ___.",
  "The rental inspection revealed ___.",
  "What is in the shoebox? ___.",
  "I was fired for ___ and rehired for ___.",
  "The camping trip is now legally referred to as ___.",
  "What killed the vibe? ___.",
  "One rule in this household: absolutely no ___.",
  "My birth was announced with the words ___.",
  "The tattoo artist begged me to reconsider ___.",
  "In hindsight, the warning sign was ___.",
  "The airline lost my luggage, which contained ___.",
  "The autopsy will list the cause as ___.",
  "What did the neighbours complain about this time? ___.",
  "The last text I sent read: ___.",
  "Never trust a man with ___.",
  "This support group is for people affected by ___.",
  "What is my toxic trait? ___.",
  "The wedding vows were interrupted by ___.",
  "I have been asked to leave over ___.",
  "Somewhere in this house there is ___.",
  "The real reason I moved cities: ___.",
  "They found ___ in the ceiling.",
  "The doctor went quiet and then said ___.",
  "My final request is ___.",
  "What's that sound coming from the spare room? ___.",
  "The species will be remembered for exactly one thing: ___.",
  "God's first draft included ___ and was immediately scrapped.",
  "Two things that must never be combined: ___ and ___.",
  "The safe word is ___.",
  "Nothing ruins a christening quite like ___.",
  "My entire sexual awakening can be traced back to ___.",
  "The last thing I heard before the ambulance: ___.",
  "It started with ___ and ended with a restraining order.",
  "The group chat has been subpoenaed over ___.",
  "I want ___ read aloud at my funeral.",
  "The bet was ___. I lost.",
  "What does the priest confess about? ___.",
  "Somewhere on the internet, there is footage of me and ___.",
  "The hospital has asked me to stop bringing in ___.",
  "My browser has flagged ___ as a recurring theme.",
  "The insurance claim simply reads: ___.",
  "The horror film opens on ___ and gets worse.",
  "Step one is ___. There is no step two.",
];

// ─── prompts that name somebody in the room ───────────────────────────────
// {player} is replaced with a real player's name, chosen fresh each round.
// These are the ones that actually end friendships.

const PERSON = [
  "{player}'s autobiography is titled ___.",
  "{player} was permanently banned from the venue for ___.",
  "The one thing {player} will never live down: ___.",
  "{player}'s dating profile leads with ___.",
  "Police found {player} in a car park with ___.",
  "{player} whispers ___ in their sleep.",
  "{player}'s last words were ___.",
  "{player} keeps ___ in the glovebox.",
  "{player} finally got the tattoo. It says ___.",
  "In the divorce, {player} fought hardest for ___.",
  "{player}'s therapist has extensive notes about ___.",
  "{player} is on a watchlist because of ___.",
  "The autopsy on {player} lists the cause as ___.",
  "{player} brought ___ to the funeral.",
  "{player} named the dog ___.",
  "{player} would trade this entire group for ___.",
  "{player}'s toxic trait is ___.",
  "{player} has been crying about ___ for three days.",
  "{player}'s deepest shame is ___.",
  "There is ___ in {player}'s shed and we are not to ask.",
  "{player} was fired on the spot for ___.",
  "{player}'s search history is almost entirely ___.",
  "{player} thinks none of us know about ___.",
  "{player} is going to die doing ___.",
  "{player} once traded ___ for ___.",
  "{player} peaked the day they discovered ___.",
  "Do not leave {player} alone with ___.",
  "{player}'s entire personality is just ___.",
  "{player} got engaged after ___.",
  "The restraining order names {player} and ___.",
  "{player} has ___ saved in their phone under a fake name.",
  "{player}'s mother still talks about ___.",
  "{player} was found in the mangroves with ___.",
  "{player} ruined Christmas with ___.",
  "{player}'s safe word is ___.",
  "{player} has a folder on their laptop containing ___.",
  "{player} was walked in on doing ___.",
  "{player} lost the bet and had to ___.",
  "{player}'s sex tape is mostly ___.",
  "{player} cried during ___ and we all heard it.",
  "{player} is banned from the group chat for sending ___.",
  "{player} will be remembered for ___ and nothing else.",
  "{player} has ___ tattooed somewhere we have all seen.",
  "The only thing keeping {player} employed is ___.",
  "{player} proposed with ___.",
];

// ─── the cards you play ───────────────────────────────────────────────────
// Short, concrete, and as bleak or as filthy as the room can handle.

const WHITE = [
  "The wet patch in my own pants",
  "Every forbidden picture I photocopied at the office",
  "A sex accident that required the fire brigade",
  "Explosive diarrhoea in a glass lift",
  "A fistful of hair that isn't mine",
  "Nan's teeth in a pint glass",
  "Crying during it",
  "Nan's vibrator, discovered during the move",
  "An erection with no explanation and appalling timing",
  "My father's second family",
  "A priest with a speedboat and a lack of judgement",
  "Uncle Baz's colonoscopy footage",
  "Dying alone in a Bunnings",
  "Whatever is fermenting in the septic tank",
  "A stiffy at a funeral",
  "Four litres of goon and one very bad decision",
  "My own vomit, recognised",
  "Being cremated in a Hawaiian shirt",
  "The exact moment the condom failed",
  "A horse that knows what it did",
  "Screaming inside an IKEA",
  "Grandma's browser history, printed and bound",
  "A tradie's arse cleavage at eye level",
  "Something structural giving way during sex",
  "Sixteen unblinking magpies",
  "My mum's OnlyFans",
  "A funeral that becomes a fistfight",
  "Being milked by a machine I bought myself",
  "The smell of a hot bin in February",
  "A stranger's tongue, uninvited",
  "Waking up in a different postcode with a new tattoo",
  "The last thing a mouse sees",
  "An esky with something breathing inside it",
  "Soiling myself at a wedding, publicly, during the vows",
  "Nine minutes of uninterrupted screaming",
  "A dog that has clearly killed before",
  "My colonoscopy, screened at the pub",
  "The part of the pool that is suspiciously warm",
  "A hand somewhere a hand was never invited",
  "Rabies from a petting zoo",
  "Two hundred kilos of prawns left in the sun",
  "My ex's entire new personality",
  "A confession made under general anaesthetic",
  "Being eaten feet first and staying polite about it",
  "A nun on the turps",
  "Whatever crawled into the wall to die",
  "An entire tub of Nutella and one fork",
  "Choking on a communion wafer",
  "The thing the ultrasound found",
  "Losing a tooth inside someone else's mouth",
  "A pelican with a full-sized rat",
  "Weeping in a McDonald's car park at 2am",
  "My uncle's mistress at Christmas lunch",
  "A colostomy bag at absolute capacity",
  "Doing 180 with the cruise control on",
  "The photos from the shed",
  "A stranger who calls me Dad and is correct",
  "A shopping trolley and twelve litres of goon",
  "The pub CCTV footage, played at my sentencing",
  "My sister's boyfriend, Kyle",
  "An open casket and a genuinely terrible haircut",
  "Vomiting into a pot plant while maintaining eye contact",
  "A cassowary that has had enough",
  "The autopsy photos",
  "Being conceived in a Tarago",
  "A hen's night that produced three separate police reports",
  "Full frontal at the RSL",
  "My last will, written on a coaster",
  "Something wriggling in the mince",
  "A nine-second hug from a sweating man",
  "The police dog being completely correct",
  "The unmistakable sound of a nappy failing",
  "My grandmother's opinion, entirely unedited",
  "Bleeding quietly at a work function",
  "A urinal that has seen better decades",
  "Something I did for two hundred dollars",
  "The neighbour's security footage",
  "Being resuscitated against my express written wishes",
  "A bucks party in a country with no extradition treaty",
  "The exact moment my father gave up on me",
  "A wet handshake that lingers far too long",
  "Half a kilo of untraceable meat",
  "Getting my stomach pumped at forty-six",
  "The stain that came back",
  "A koala with an attitude and a diagnosis",
  "My therapist's face when I finished the story",
  "A tampon in a champagne flute",
  "Whatever the tide brought in",
  "A slow, deliberate blink from a goanna",
  "Nan on the pokies at 3am with my inheritance",
  "Something my body did in public without asking me",
  "The full contents of my glovebox",
  "Being described in court only as 'the male'",
  "A grown man weeping inside a jumping castle",
  "A gender reveal that took out the shed",
  "Two hundred unread texts from Baz",
  "The thing living under the deck",
  "Getting glassed at a christening",
  "My honest weight",
  "A sausage sizzle that ended in police attendance",
  "Sweating clean through a linen suit at the eulogy",
  "A stranger's dentures in my bag",
  "Being chased by an emu I personally provoked",
  "The wet crunch of something load-bearing",
  "A Bali trip that produced a child",
  "Whatever is growing in the shower grout",
  "A eulogy that names names",
  "My father's browser history, discovered too late",
  "A hire car returned wet",
  "Getting the ick during my own wedding",
  "A goanna in the nappy bin",
  "Being the reason for the hose-down",
  "Nine hours in a Bali holding cell",
  "A dead pet in the good freezer",
  "My aunt's third divorce party",
  "The lump",
  "A tinnie, a rifle, and no particular plan",
  "The specific noise my father makes",
  "Waking up handcuffed to a chair I now legally own",
  "A christening that required stitches",
  "My legal team's collective face",
  "A magpie that goes for the eyes",
  "Something in the salad that moved",
  "Being escorted out of Sizzler by three men",
  "The wedding video, uncut and unedited",
  "A meat tray won and immediately regretted",
  "A rash I got from the couch",
  "My uncle's alibi",
  "A public toilet with genuine ambition",
  "Two blokes and a wheelie bin",
  "The moment my mother walked in",
  "Being found in the mangroves",
  "A wet fart during the vows",
  "My family's group chat, leaked in full",
  "Whatever the dog rolled in",
  "A funeral pie that had turned",
  "Being the punchline at my own wake",
  "Nine dollars of servo sushi",
  "The smell of a caravan in summer",
  "Getting bitten by something in the toilet",
  "My best mate's OnlyFans",
  "A hot tub of deeply questionable water",
  "The bit they had to surgically remove",
  "Being lowered into the ground badly",
  "An unflushed act of war",
  "My mother's hen's night photos",
  "A cat that watched the entire thing without blinking",
  "Getting my head stuck in the fence again",
  "The bucket by the bed",
  "Being described by paramedics only as 'the smell'",
  "Six hours locked in a portaloo",
  "A vasectomy performed with unusual enthusiasm",
  "The thing in the drain",
  "Getting engaged out of pure panic",
  "A dead uncle's DVD collection",
  "Being loved by something with far too many legs",
  "Nan's ashes in a Woolworths bag",
  "A wedding cake with something inside it",
  "My blood alcohol reading, read aloud",
  "Getting my hand stuck in a vending machine",
  "A group hug I did not consent to",
  "My hairline, in real time",
  "Whatever ran across my foot",
  "Being the reason the pool closed permanently",
  "The stain on the mattress I inherited",
  "Food poisoning at my own engagement party",
  "A boil, lanced publicly",
  "My uncle's shed and its actual purpose",
  "Being tased by a family member",
  "The full weight of a wet dog",
  "A stranger sobbing in my Uber",
  "My final, deeply humiliating request",
  "A snake in the dunny",
  "Being caught on the neighbour's doorbell camera",
  "The last thing the paramedics said to each other",
  "A jar in the shed with the lid screwed on tight",
  "My mother, live on air",
  "Something regrettable involving a jetty",
  "Being buried in the wrong plot",
  "A wet tissue passed hand to hand",
  "My colon, on a screen, at Christmas",
  "A stranger's pubic hair in the soap",
  "The hole",
  "Something that should have stayed on the inside",
  "A wedding night that required a plumber",
  "My uncle's magazines, still under the bed",
  "Getting caught in the act by a cockatoo",
  "The precise sound of a body hitting a trampoline",
  "Something unspeakable in the caravan",
  "My mother's reaction to the video",
  "A stranger's tooth in my hand",
  "A sexual awakening at a Bunnings sausage sizzle",
  "The photos the police described as 'unusual'",
  "Whatever is crusted on the remote",
  "A grown man stuck in a slide",
  "The darker patch of the mattress",
  "Six seconds of eye contact and a lifelong mistake",
  "A man crying into a bain-marie",
  "The full spectrum of what a body can produce",
  "A hernia, live on stage",
  "Whatever fell out of me at the airport",
  "My browser history, read aloud at my funeral",
  "Getting stuck in the bean bag",
  "My final act, caught on servo CCTV",
  "The taste of a decision",
  "A sneeze that ended the marriage",
  "Getting a limb somewhere it was never invited",
  "The smell of a man who has completely given up",
  "Two litres of anything, straight down",
  "My own name, screamed by a total stranger",
  "The sound of my father discovering the tapes",
  "An entire extended family watching me fail",
  "A cursed esky",
  "The last surviving Bunnings sausage",
  "My father's unopened letters",
  "The sound my knee makes now",
  "Unsupervised children",
  "Something enormous living in the roof cavity",
  "The soft parts",
  "My mother's disappointment, notarised",
  "The smell of a servo at 3am",
  "Screaming into a jar and selling it",
  "The full and unedited footage",
  "Two men named Baz",
  "The wet part of the couch",
  "A bin chicken with dead eyes",
  "Nine hours of dashcam footage",
  "Somebody else's medication",
  "A jumping castle in high wind",
  "The last thing the smoke alarm heard",
  "Whatever happened in Bali",
  "The queue for the one working toilet",
  "Something I found in a bin and kept",
  "My legal name, which is not the one you know",
  "A pub carpet that has seen things",
  "A haunted air fryer",
  "Whatever this rash is",
  "The one photo that must never surface",
  "Reheating fish in a shared office",
  "The door in my parents' house that never opens",
  "A meat raffle gone catastrophically wrong",
  "My uncle's business idea",
  "One bathroom, nine housemates",
  "Sending it to the wrong Sarah",
  "Peeling",
  "The thing I said to the police",
  "My search for meaning, and also a toilet",
  "A phone dropped in a public toilet and retrieved by hand",
  "The unlabelled thing in the freezer",
  "The noise from the room next door",
  "Confidently entering the wrong house",
  "The group's collective bail money",
  "A dance move that requires a waiver",
  "Somebody's dad in a hot tub",
  "A shed with a purpose I will not disclose",
  "An air mattress slowly deflating beneath us",
  "The couch that came from the street",
  "Whatever the doctor said not to do",
  "A cake with the wrong name on it",
  "A shopping trolley in a river",
  "A man who owns three jet skis and no house",
  "The smell in the car after the beach",
  "My contribution to the divorce",
  "The fridge nobody will claim",
  "An unbroken eight-year run of poor decisions",
];

// ─── round rotation ───────────────────────────────────────────────────────
// Rounds cycle through this pattern rather than one big shuffle, so the
// "who here" questions come around reliably instead of vanishing for
// twenty rounds. Each type draws from its own pile.

const PATTERN = [
  "pick",
  "hand",
  "text",
  "pick",
  "person",
  "hand",
  "pick",
  "text",
  "person",
  "hand",
];

// ─── assembled ────────────────────────────────────────────────────────────

const blanksIn = (text) => (text.match(/_{2,}/g) || []).length;

const DECK = [
  ...PICK.map((text) => ({ text, type: "pick" })),
  ...TEXT.map((text) => ({ text, type: "text" })),
  ...BLACK.map((text) => ({ text, type: "hand", blanks: blanksIn(text) || 1 })),
  ...PERSON.map((text) => ({
    text,
    type: "person",
    play: "hand", // played from your hand, just like a black card
    blanks: blanksIn(text) || 1,
    person: true,
  })),
];

module.exports = { DECK, WHITE, PICK, TEXT, BLACK, PERSON, PATTERN };
